/*
HOOD CustomProductReviews Resources 1.08
- Inserts canonical + lowercase resource names.
- Applies to every active language in nopCommerce [Language] table.
- Uses LanguageCulture / UniqueSeoCode / Name for translation matching.
*/

DECLARE @R TABLE(ResourceName nvarchar(400), Lang nvarchar(20), ResourceValue nvarchar(max));

INSERT INTO @R(ResourceName, Lang, ResourceValue)
VALUES
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'en', N'Product reviews for'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'en', N'Product reviews for'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'en', N'Attach files'),
(N'plugins.widgets.customproductreviews.attachfiles', N'en', N'Attach files'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'en', N'Maximum files in upload: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'en', N'Maximum files in upload: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'en', N'Hover to zoom'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'en', N'Hover to zoom'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'en', N'View larger review photo'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'en', N'View larger review photo'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'en', N'Review video'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'en', N'Review video'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'en', N'Your browser does not support the video tag.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'en', N'Your browser does not support the video tag.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'en', N'Your uploaded media will continue to be processed in the background.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'en', N'Your uploaded media will continue to be processed in the background.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'en', N'After processing, the media will be automatically added to your review.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'en', N'After processing, the media will be automatically added to your review.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'en', N'File format is not supported for upload.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'en', N'File format is not supported for upload.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'en', N'Upload file format error.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'en', N'Upload file format error.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'en', N'A general error occurred. Please try again.'),
(N'plugins.widgets.customproductreviews.generalerror', N'en', N'A general error occurred. Please try again.'),
(N'Product Reviews For', N'en', N'Product reviews for'),
(N'Product Reviews For ', N'en', N'Product reviews for'),
(N'product reviews for', N'en', N'Product reviews for'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'tr', N'Ürün yorumları:'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'tr', N'Ürün yorumları:'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'tr', N'Dosya ekle'),
(N'plugins.widgets.customproductreviews.attachfiles', N'tr', N'Dosya ekle'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'tr', N'Yüklenebilecek maksimum dosya sayısı: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'tr', N'Yüklenebilecek maksimum dosya sayısı: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'tr', N'Büyütmek için üzerine gel'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'tr', N'Büyütmek için üzerine gel'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'tr', N'Yorum fotoğrafını büyüt'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'tr', N'Yorum fotoğrafını büyüt'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'tr', N'Yorum videosu'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'tr', N'Yorum videosu'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'tr', N'Tarayıcınız video etiketini desteklemiyor.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'tr', N'Tarayıcınız video etiketini desteklemiyor.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'tr', N'Yüklediğiniz medya arka planda işlenmeye devam edecek.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'tr', N'Yüklediğiniz medya arka planda işlenmeye devam edecek.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'tr', N'İşlem tamamlandığında medya otomatik olarak yorumunuza eklenecek.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'tr', N'İşlem tamamlandığında medya otomatik olarak yorumunuza eklenecek.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'tr', N'Dosya formatı yükleme için desteklenmiyor.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'tr', N'Dosya formatı yükleme için desteklenmiyor.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'tr', N'Dosya yükleme format hatası.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'tr', N'Dosya yükleme format hatası.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'tr', N'Genel bir hata oluştu. Lütfen tekrar deneyin.'),
(N'plugins.widgets.customproductreviews.generalerror', N'tr', N'Genel bir hata oluştu. Lütfen tekrar deneyin.'),
(N'Product Reviews For', N'tr', N'Ürün yorumları:'),
(N'Product Reviews For ', N'tr', N'Ürün yorumları:'),
(N'product reviews for', N'tr', N'Ürün yorumları:'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'de', N'Produktbewertungen für'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'de', N'Produktbewertungen für'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'de', N'Dateien anhängen'),
(N'plugins.widgets.customproductreviews.attachfiles', N'de', N'Dateien anhängen'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'de', N'Maximale Anzahl Dateien: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'de', N'Maximale Anzahl Dateien: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'de', N'Zum Vergrößern darüberfahren'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'de', N'Zum Vergrößern darüberfahren'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'de', N'Bewertungsfoto vergrößern'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'de', N'Bewertungsfoto vergrößern'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'de', N'Bewertungsvideo'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'de', N'Bewertungsvideo'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'de', N'Ihr Browser unterstützt das Video-Tag nicht.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'de', N'Ihr Browser unterstützt das Video-Tag nicht.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'de', N'Ihre hochgeladenen Medien werden im Hintergrund weiter verarbeitet.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'de', N'Ihre hochgeladenen Medien werden im Hintergrund weiter verarbeitet.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'de', N'Nach der Verarbeitung werden die Medien automatisch Ihrer Bewertung hinzugefügt.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'de', N'Nach der Verarbeitung werden die Medien automatisch Ihrer Bewertung hinzugefügt.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'de', N'Das Dateiformat wird für den Upload nicht unterstützt.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'de', N'Das Dateiformat wird für den Upload nicht unterstützt.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'de', N'Fehler beim Upload-Dateiformat.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'de', N'Fehler beim Upload-Dateiformat.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'de', N'Ein allgemeiner Fehler ist aufgetreten. Bitte versuchen Sie es erneut.'),
(N'plugins.widgets.customproductreviews.generalerror', N'de', N'Ein allgemeiner Fehler ist aufgetreten. Bitte versuchen Sie es erneut.'),
(N'Product Reviews For', N'de', N'Produktbewertungen für'),
(N'Product Reviews For ', N'de', N'Produktbewertungen für'),
(N'product reviews for', N'de', N'Produktbewertungen für'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'fr', N'Avis produit pour'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'fr', N'Avis produit pour'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'fr', N'Joindre des fichiers'),
(N'plugins.widgets.customproductreviews.attachfiles', N'fr', N'Joindre des fichiers'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'fr', N'Nombre maximal de fichiers : {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'fr', N'Nombre maximal de fichiers : {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'fr', N'Survolez pour zoomer'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'fr', N'Survolez pour zoomer'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'fr', N'Agrandir la photo de l’avis'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'fr', N'Agrandir la photo de l’avis'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'fr', N'Vidéo de l’avis'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'fr', N'Vidéo de l’avis'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'fr', N'Votre navigateur ne prend pas en charge la balise vidéo.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'fr', N'Votre navigateur ne prend pas en charge la balise vidéo.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'fr', N'Vos médias téléversés continueront à être traités en arrière-plan.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'fr', N'Vos médias téléversés continueront à être traités en arrière-plan.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'fr', N'Après traitement, les médias seront ajoutés automatiquement à votre avis.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'fr', N'Après traitement, les médias seront ajoutés automatiquement à votre avis.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'fr', N'Le format de fichier n’est pas pris en charge pour le téléversement.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'fr', N'Le format de fichier n’est pas pris en charge pour le téléversement.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'fr', N'Erreur de format de fichier téléversé.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'fr', N'Erreur de format de fichier téléversé.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'fr', N'Une erreur générale s’est produite. Veuillez réessayer.'),
(N'plugins.widgets.customproductreviews.generalerror', N'fr', N'Une erreur générale s’est produite. Veuillez réessayer.'),
(N'Product Reviews For', N'fr', N'Avis produit pour'),
(N'Product Reviews For ', N'fr', N'Avis produit pour'),
(N'product reviews for', N'fr', N'Avis produit pour'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'es', N'Reseñas del producto para'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'es', N'Reseñas del producto para'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'es', N'Adjuntar archivos'),
(N'plugins.widgets.customproductreviews.attachfiles', N'es', N'Adjuntar archivos'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'es', N'Máximo de archivos: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'es', N'Máximo de archivos: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'es', N'Pasa el cursor para ampliar'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'es', N'Pasa el cursor para ampliar'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'es', N'Ver foto de reseña ampliada'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'es', N'Ver foto de reseña ampliada'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'es', N'Vídeo de la reseña'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'es', N'Vídeo de la reseña'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'es', N'Tu navegador no admite la etiqueta de vídeo.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'es', N'Tu navegador no admite la etiqueta de vídeo.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'es', N'Tus archivos multimedia se seguirán procesando en segundo plano.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'es', N'Tus archivos multimedia se seguirán procesando en segundo plano.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'es', N'Después del procesamiento, los archivos se añadirán automáticamente a tu reseña.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'es', N'Después del procesamiento, los archivos se añadirán automáticamente a tu reseña.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'es', N'El formato del archivo no es compatible para la carga.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'es', N'El formato del archivo no es compatible para la carga.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'es', N'Error de formato del archivo cargado.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'es', N'Error de formato del archivo cargado.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'es', N'Se produjo un error general. Inténtalo de nuevo.'),
(N'plugins.widgets.customproductreviews.generalerror', N'es', N'Se produjo un error general. Inténtalo de nuevo.'),
(N'Product Reviews For', N'es', N'Reseñas del producto para'),
(N'Product Reviews For ', N'es', N'Reseñas del producto para'),
(N'product reviews for', N'es', N'Reseñas del producto para'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'it', N'Recensioni prodotto per'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'it', N'Recensioni prodotto per'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'it', N'Allega file'),
(N'plugins.widgets.customproductreviews.attachfiles', N'it', N'Allega file'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'it', N'Numero massimo di file: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'it', N'Numero massimo di file: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'it', N'Passa sopra per ingrandire'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'it', N'Passa sopra per ingrandire'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'it', N'Visualizza foto recensione ingrandita'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'it', N'Visualizza foto recensione ingrandita'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'it', N'Video recensione'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'it', N'Video recensione'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'it', N'Il tuo browser non supporta il tag video.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'it', N'Il tuo browser non supporta il tag video.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'it', N'I media caricati continueranno a essere elaborati in background.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'it', N'I media caricati continueranno a essere elaborati in background.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'it', N'Dopo l’elaborazione, i media saranno aggiunti automaticamente alla recensione.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'it', N'Dopo l’elaborazione, i media saranno aggiunti automaticamente alla recensione.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'it', N'Il formato del file non è supportato per il caricamento.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'it', N'Il formato del file non è supportato per il caricamento.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'it', N'Errore nel formato del file caricato.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'it', N'Errore nel formato del file caricato.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'it', N'Si è verificato un errore generale. Riprova.'),
(N'plugins.widgets.customproductreviews.generalerror', N'it', N'Si è verificato un errore generale. Riprova.'),
(N'Product Reviews For', N'it', N'Recensioni prodotto per'),
(N'Product Reviews For ', N'it', N'Recensioni prodotto per'),
(N'product reviews for', N'it', N'Recensioni prodotto per'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'nl', N'Productbeoordelingen voor'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'nl', N'Productbeoordelingen voor'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'nl', N'Bestanden bijvoegen'),
(N'plugins.widgets.customproductreviews.attachfiles', N'nl', N'Bestanden bijvoegen'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'nl', N'Maximaal aantal bestanden: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'nl', N'Maximaal aantal bestanden: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'nl', N'Beweeg erover om te zoomen'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'nl', N'Beweeg erover om te zoomen'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'nl', N'Bekijk grotere reviewfoto'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'nl', N'Bekijk grotere reviewfoto'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'nl', N'Reviewvideo'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'nl', N'Reviewvideo'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'nl', N'Uw browser ondersteunt de videotag niet.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'nl', N'Uw browser ondersteunt de videotag niet.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'nl', N'Uw geüploade media worden op de achtergrond verder verwerkt.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'nl', N'Uw geüploade media worden op de achtergrond verder verwerkt.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'nl', N'Na verwerking worden de media automatisch aan uw beoordeling toegevoegd.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'nl', N'Na verwerking worden de media automatisch aan uw beoordeling toegevoegd.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'nl', N'Het bestandsformaat wordt niet ondersteund voor uploaden.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'nl', N'Het bestandsformaat wordt niet ondersteund voor uploaden.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'nl', N'Fout in uploadbestandsformaat.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'nl', N'Fout in uploadbestandsformaat.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'nl', N'Er is een algemene fout opgetreden. Probeer het opnieuw.'),
(N'plugins.widgets.customproductreviews.generalerror', N'nl', N'Er is een algemene fout opgetreden. Probeer het opnieuw.'),
(N'Product Reviews For', N'nl', N'Productbeoordelingen voor'),
(N'Product Reviews For ', N'nl', N'Productbeoordelingen voor'),
(N'product reviews for', N'nl', N'Productbeoordelingen voor'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'ru', N'Отзывы о товаре'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'ru', N'Отзывы о товаре'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'ru', N'Прикрепить файлы'),
(N'plugins.widgets.customproductreviews.attachfiles', N'ru', N'Прикрепить файлы'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'ru', N'Максимальное количество файлов: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'ru', N'Максимальное количество файлов: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'ru', N'Наведите для увеличения'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'ru', N'Наведите для увеличения'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'ru', N'Увеличить фото отзыва'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'ru', N'Увеличить фото отзыва'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'ru', N'Видео отзыва'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'ru', N'Видео отзыва'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'ru', N'Ваш браузер не поддерживает видео.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'ru', N'Ваш браузер не поддерживает видео.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'ru', N'Загруженные медиа будут обработаны в фоновом режиме.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'ru', N'Загруженные медиа будут обработаны в фоновом режиме.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'ru', N'После обработки медиа будут автоматически добавлены к отзыву.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'ru', N'После обработки медиа будут автоматически добавлены к отзыву.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'ru', N'Формат файла не поддерживается для загрузки.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'ru', N'Формат файла не поддерживается для загрузки.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'ru', N'Ошибка формата загружаемого файла.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'ru', N'Ошибка формата загружаемого файла.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'ru', N'Произошла ошибка. Пожалуйста, попробуйте снова.'),
(N'plugins.widgets.customproductreviews.generalerror', N'ru', N'Произошла ошибка. Пожалуйста, попробуйте снова.'),
(N'Product Reviews For', N'ru', N'Отзывы о товаре'),
(N'Product Reviews For ', N'ru', N'Отзывы о товаре'),
(N'product reviews for', N'ru', N'Отзывы о товаре'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'ar', N'مراجعات المنتج لـ'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'ar', N'مراجعات المنتج لـ'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'ar', N'إرفاق ملفات'),
(N'plugins.widgets.customproductreviews.attachfiles', N'ar', N'إرفاق ملفات'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'ar', N'الحد الأقصى لعدد الملفات: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'ar', N'الحد الأقصى لعدد الملفات: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'ar', N'مرّر للتكبير'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'ar', N'مرّر للتكبير'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'ar', N'عرض صورة المراجعة بحجم أكبر'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'ar', N'عرض صورة المراجعة بحجم أكبر'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'ar', N'فيديو المراجعة'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'ar', N'فيديو المراجعة'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'ar', N'متصفحك لا يدعم وسم الفيديو.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'ar', N'متصفحك لا يدعم وسم الفيديو.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'ar', N'سيستمر معالجة الوسائط المرفوعة في الخلفية.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'ar', N'سيستمر معالجة الوسائط المرفوعة في الخلفية.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'ar', N'بعد المعالجة، ستتم إضافة الوسائط تلقائيًا إلى مراجعتك.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'ar', N'بعد المعالجة، ستتم إضافة الوسائط تلقائيًا إلى مراجعتك.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'ar', N'تنسيق الملف غير مدعوم للرفع.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'ar', N'تنسيق الملف غير مدعوم للرفع.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'ar', N'خطأ في تنسيق الملف المرفوع.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'ar', N'خطأ في تنسيق الملف المرفوع.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'ar', N'حدث خطأ عام. يرجى المحاولة مرة أخرى.'),
(N'plugins.widgets.customproductreviews.generalerror', N'ar', N'حدث خطأ عام. يرجى المحاولة مرة أخرى.'),
(N'Product Reviews For', N'ar', N'مراجعات المنتج لـ'),
(N'Product Reviews For ', N'ar', N'مراجعات المنتج لـ'),
(N'product reviews for', N'ar', N'مراجعات المنتج لـ'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'pt', N'Avaliações do produto para'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'pt', N'Avaliações do produto para'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'pt', N'Anexar arquivos'),
(N'plugins.widgets.customproductreviews.attachfiles', N'pt', N'Anexar arquivos'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'pt', N'Máximo de arquivos: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'pt', N'Máximo de arquivos: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'pt', N'Passe o mouse para ampliar'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'pt', N'Passe o mouse para ampliar'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'pt', N'Ver foto da avaliação ampliada'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'pt', N'Ver foto da avaliação ampliada'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'pt', N'Vídeo da avaliação'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'pt', N'Vídeo da avaliação'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'pt', N'Seu navegador não suporta a tag de vídeo.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'pt', N'Seu navegador não suporta a tag de vídeo.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'pt', N'A mídia enviada continuará sendo processada em segundo plano.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'pt', N'A mídia enviada continuará sendo processada em segundo plano.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'pt', N'Após o processamento, a mídia será adicionada automaticamente à sua avaliação.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'pt', N'Após o processamento, a mídia será adicionada automaticamente à sua avaliação.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'pt', N'O formato do arquivo não é compatível para upload.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'pt', N'O formato do arquivo não é compatível para upload.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'pt', N'Erro de formato do arquivo enviado.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'pt', N'Erro de formato do arquivo enviado.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'pt', N'Ocorreu um erro geral. Tente novamente.'),
(N'plugins.widgets.customproductreviews.generalerror', N'pt', N'Ocorreu um erro geral. Tente novamente.'),
(N'Product Reviews For', N'pt', N'Avaliações do produto para'),
(N'Product Reviews For ', N'pt', N'Avaliações do produto para'),
(N'product reviews for', N'pt', N'Avaliações do produto para'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'pl', N'Opinie produktu dla'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'pl', N'Opinie produktu dla'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'pl', N'Dołącz pliki'),
(N'plugins.widgets.customproductreviews.attachfiles', N'pl', N'Dołącz pliki'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'pl', N'Maksymalna liczba plików: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'pl', N'Maksymalna liczba plików: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'pl', N'Najedź, aby powiększyć'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'pl', N'Najedź, aby powiększyć'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'pl', N'Powiększ zdjęcie z opinii'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'pl', N'Powiększ zdjęcie z opinii'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'pl', N'Film z opinii'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'pl', N'Film z opinii'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'pl', N'Twoja przeglądarka nie obsługuje znacznika wideo.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'pl', N'Twoja przeglądarka nie obsługuje znacznika wideo.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'pl', N'Przesłane media będą dalej przetwarzane w tle.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'pl', N'Przesłane media będą dalej przetwarzane w tle.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'pl', N'Po przetworzeniu media zostaną automatycznie dodane do opinii.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'pl', N'Po przetworzeniu media zostaną automatycznie dodane do opinii.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'pl', N'Format pliku nie jest obsługiwany.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'pl', N'Format pliku nie jest obsługiwany.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'pl', N'Błąd formatu przesyłanego pliku.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'pl', N'Błąd formatu przesyłanego pliku.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'pl', N'Wystąpił błąd ogólny. Spróbuj ponownie.'),
(N'plugins.widgets.customproductreviews.generalerror', N'pl', N'Wystąpił błąd ogólny. Spróbuj ponownie.'),
(N'Product Reviews For', N'pl', N'Opinie produktu dla'),
(N'Product Reviews For ', N'pl', N'Opinie produktu dla'),
(N'product reviews for', N'pl', N'Opinie produktu dla'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'zh', N'产品评价：'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'zh', N'产品评价：'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'zh', N'附加文件'),
(N'plugins.widgets.customproductreviews.attachfiles', N'zh', N'附加文件'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'zh', N'最多上传文件数：{0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'zh', N'最多上传文件数：{0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'zh', N'悬停放大'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'zh', N'悬停放大'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'zh', N'查看更大的评价图片'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'zh', N'查看更大的评价图片'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'zh', N'评价视频'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'zh', N'评价视频'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'zh', N'您的浏览器不支持视频标签。'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'zh', N'您的浏览器不支持视频标签。'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'zh', N'您上传的媒体将继续在后台处理。'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'zh', N'您上传的媒体将继续在后台处理。'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'zh', N'处理完成后，媒体将自动添加到您的评价中。'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'zh', N'处理完成后，媒体将自动添加到您的评价中。'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'zh', N'不支持上传此文件格式。'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'zh', N'不支持上传此文件格式。'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'zh', N'上传文件格式错误。'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'zh', N'上传文件格式错误。'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'zh', N'发生一般错误。请重试。'),
(N'plugins.widgets.customproductreviews.generalerror', N'zh', N'发生一般错误。请重试。'),
(N'Product Reviews For', N'zh', N'产品评价：'),
(N'Product Reviews For ', N'zh', N'产品评价：'),
(N'product reviews for', N'zh', N'产品评价：'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'ja', N'商品のレビュー：'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'ja', N'商品のレビュー：'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'ja', N'ファイルを添付'),
(N'plugins.widgets.customproductreviews.attachfiles', N'ja', N'ファイルを添付'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'ja', N'最大アップロードファイル数: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'ja', N'最大アップロードファイル数: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'ja', N'ホバーして拡大'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'ja', N'ホバーして拡大'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'ja', N'レビュー写真を拡大表示'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'ja', N'レビュー写真を拡大表示'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'ja', N'レビュー動画'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'ja', N'レビュー動画'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'ja', N'お使いのブラウザは video タグに対応していません。'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'ja', N'お使いのブラウザは video タグに対応していません。'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'ja', N'アップロードされたメディアはバックグラウンドで処理されます。'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'ja', N'アップロードされたメディアはバックグラウンドで処理されます。'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'ja', N'処理後、メディアは自動的にレビューに追加されます。'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'ja', N'処理後、メディアは自動的にレビューに追加されます。'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'ja', N'このファイル形式はアップロードに対応していません。'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'ja', N'このファイル形式はアップロードに対応していません。'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'ja', N'アップロードファイル形式エラー。'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'ja', N'アップロードファイル形式エラー。'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'ja', N'一般的なエラーが発生しました。もう一度お試しください。'),
(N'plugins.widgets.customproductreviews.generalerror', N'ja', N'一般的なエラーが発生しました。もう一度お試しください。'),
(N'Product Reviews For', N'ja', N'商品のレビュー：'),
(N'Product Reviews For ', N'ja', N'商品のレビュー：'),
(N'product reviews for', N'ja', N'商品のレビュー：'),
(N'Plugins.Widgets.CustomProductReviews.ProductReviewsFor', N'ko', N'제품 리뷰:'),
(N'plugins.widgets.customproductreviews.productreviewsfor', N'ko', N'제품 리뷰:'),
(N'Plugins.Widgets.CustomProductReviews.AttachFiles', N'ko', N'파일 첨부'),
(N'plugins.widgets.customproductreviews.attachfiles', N'ko', N'파일 첨부'),
(N'Plugins.Widgets.CustomProductReviews.MaxFilesInUpload', N'ko', N'최대 업로드 파일 수: {0}'),
(N'plugins.widgets.customproductreviews.maxfilesinupload', N'ko', N'최대 업로드 파일 수: {0}'),
(N'Plugins.Widgets.CustomProductReviews.HoverToZoom', N'ko', N'확대하려면 마우스를 올리세요'),
(N'plugins.widgets.customproductreviews.hovertozoom', N'ko', N'확대하려면 마우스를 올리세요'),
(N'Plugins.Widgets.CustomProductReviews.ViewLargerReviewPhoto', N'ko', N'리뷰 사진 크게 보기'),
(N'plugins.widgets.customproductreviews.viewlargerreviewphoto', N'ko', N'리뷰 사진 크게 보기'),
(N'Plugins.Widgets.CustomProductReviews.ReviewVideo', N'ko', N'리뷰 동영상'),
(N'plugins.widgets.customproductreviews.reviewvideo', N'ko', N'리뷰 동영상'),
(N'Plugins.Widgets.CustomProductReviews.VideoNotSupported', N'ko', N'브라우저가 video 태그를 지원하지 않습니다.'),
(N'plugins.widgets.customproductreviews.videonotsupported', N'ko', N'브라우저가 video 태그를 지원하지 않습니다.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingStarted', N'ko', N'업로드한 미디어가 백그라운드에서 계속 처리됩니다.'),
(N'plugins.widgets.customproductreviews.mediaprocessingstarted', N'ko', N'업로드한 미디어가 백그라운드에서 계속 처리됩니다.'),
(N'Plugins.Widgets.CustomProductReviews.MediaProcessingCompletedAutomatically', N'ko', N'처리가 완료되면 미디어가 자동으로 리뷰에 추가됩니다.'),
(N'plugins.widgets.customproductreviews.mediaprocessingcompletedautomatically', N'ko', N'처리가 완료되면 미디어가 자동으로 리뷰에 추가됩니다.'),
(N'Plugins.Widgets.CustomProductReviews.UnsupportedFileFormat', N'ko', N'업로드할 수 없는 파일 형식입니다.'),
(N'plugins.widgets.customproductreviews.unsupportedfileformat', N'ko', N'업로드할 수 없는 파일 형식입니다.'),
(N'Plugins.Widgets.CustomProductReviews.UploadFileFormatError', N'ko', N'업로드 파일 형식 오류.'),
(N'plugins.widgets.customproductreviews.uploadfileformaterror', N'ko', N'업로드 파일 형식 오류.'),
(N'Plugins.Widgets.CustomProductReviews.GeneralError', N'ko', N'일반 오류가 발생했습니다. 다시 시도하세요.'),
(N'plugins.widgets.customproductreviews.generalerror', N'ko', N'일반 오류가 발생했습니다. 다시 시도하세요.'),
(N'Product Reviews For', N'ko', N'제품 리뷰:'),
(N'Product Reviews For ', N'ko', N'제품 리뷰:'),
(N'product reviews for', N'ko', N'제품 리뷰:');

WITH L AS (
    SELECT
        Id,
        CASE
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'tr%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'tr%' OR LOWER(ISNULL(Name,'')) LIKE '%turk%' OR LOWER(ISNULL(Name,'')) LIKE N'%türk%' THEN N'tr'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'de%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'de%' OR LOWER(ISNULL(Name,'')) LIKE '%german%' OR LOWER(ISNULL(Name,'')) LIKE '%deutsch%' THEN N'de'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'fr%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'fr%' OR LOWER(ISNULL(Name,'')) LIKE '%french%' OR LOWER(ISNULL(Name,'')) LIKE '%fran%' THEN N'fr'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'es%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'es%' OR LOWER(ISNULL(Name,'')) LIKE '%spanish%' OR LOWER(ISNULL(Name,'')) LIKE '%espa%' THEN N'es'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'it%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'it%' OR LOWER(ISNULL(Name,'')) LIKE '%ital%' THEN N'it'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'nl%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'nl%' OR LOWER(ISNULL(Name,'')) LIKE '%dutch%' OR LOWER(ISNULL(Name,'')) LIKE '%neder%' THEN N'nl'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'ru%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'ru%' OR LOWER(ISNULL(Name,'')) LIKE '%russian%' OR LOWER(ISNULL(Name,'')) LIKE N'%рус%' THEN N'ru'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'ar%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'ar%' OR LOWER(ISNULL(Name,'')) LIKE '%arab%' THEN N'ar'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'pt%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'pt%' OR LOWER(ISNULL(Name,'')) LIKE '%portugu%' THEN N'pt'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'pl%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'pl%' OR LOWER(ISNULL(Name,'')) LIKE '%polish%' OR LOWER(ISNULL(Name,'')) LIKE '%polski%' THEN N'pl'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'zh%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'zh%' OR LOWER(ISNULL(Name,'')) LIKE '%chinese%' THEN N'zh'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'ja%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'ja%' OR LOWER(ISNULL(Name,'')) LIKE '%japanese%' THEN N'ja'
            WHEN LOWER(ISNULL(UniqueSeoCode,'')) LIKE 'ko%' OR LOWER(ISNULL(LanguageCulture,'')) LIKE 'ko%' OR LOWER(ISNULL(Name,'')) LIKE '%korean%' THEN N'ko'
            ELSE N'en'
        END AS Lang
    FROM [Language]
),
Pairs AS (
    SELECT L.Id AS LanguageId, R.ResourceName, R.ResourceValue
    FROM L
    JOIN @R R ON R.Lang = L.Lang

    UNION ALL

    SELECT L.Id AS LanguageId, R.ResourceName, R.ResourceValue
    FROM L
    JOIN @R R ON R.Lang = N'en'
    WHERE NOT EXISTS (
        SELECT 1
        FROM @R RX
        WHERE RX.Lang = L.Lang AND RX.ResourceName = R.ResourceName
    )
),
Dedup AS (
    SELECT LanguageId, ResourceName, MAX(ResourceValue) AS ResourceValue
    FROM Pairs
    GROUP BY LanguageId, ResourceName
)
MERGE LocaleStringResource AS T
USING Dedup AS S
ON T.LanguageId = S.LanguageId AND T.ResourceName = S.ResourceName
WHEN MATCHED THEN
    UPDATE SET T.ResourceValue = S.ResourceValue
WHEN NOT MATCHED THEN
    INSERT(LanguageId, ResourceName, ResourceValue)
    VALUES(S.LanguageId, S.ResourceName, S.ResourceValue);

SELECT
    L.Id AS LanguageId,
    L.Name,
    L.LanguageCulture,
    L.UniqueSeoCode,
    COUNT(LSR.Id) AS CustomProductReviewResourceCount
FROM [Language] L
LEFT JOIN LocaleStringResource LSR
    ON LSR.LanguageId = L.Id
   AND LOWER(LSR.ResourceName) LIKE 'plugins.widgets.customproductreviews.%'
GROUP BY L.Id, L.Name, L.LanguageCulture, L.UniqueSeoCode
ORDER BY L.Id;