<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputPath>..\..\Presentation\Nop.Web\Plugins\Payments.StripeZip</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <ImplicitUsings>enable</ImplicitUsings>
    <Copyright>Genius Software</Copyright>
    <Company>Genius Software</Company>
    <Authors>Genius Software</Authors>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logo.png" />
    <None Remove="plugin.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Nop.Plugin.Payments.StripeBnpl.Shared\StripeBnplPaymentMethodBase.cs" Link="StripeBnplPaymentMethodBase.cs" />
    <Content Include="logo.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="plugin.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nop.Plugin.Misc.StripeBnplCore\Nop.Plugin.Misc.StripeBnplCore.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Services\Nop.Services.csproj" />
    <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>

  <Target Name="NopTarget" AfterTargets="Build">
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />
  </Target>
</Project>
